spring.application.name=ssl
server.port=7443

server.ssl.key-store=classpath:localhost.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit

server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2
server.ssl.ciphers=TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA

spring.security.oauth2.client.registration.casdoor.client-id=5ff49241c4dfdfac7cff
spring.security.oauth2.client.registration.casdoor.client-secret=9cb1751bc13a038fae3354f6806f95966543edaf
spring.security.oauth2.client.registration.casdoor.scope=openid,profile,email
spring.security.oauth2.client.registration.casdoor.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.casdoor.redirect-uri=https://localhost:7443/login/oauth2/code/casdoor

spring.security.oauth2.client.provider.casdoor.authorization-uri=http://localhost:8000/login/oauth/authorize
spring.security.oauth2.client.provider.casdoor.token-uri=http://localhost:8000/api/login/oauth/access_token
spring.security.oauth2.client.provider.casdoor.user-info-uri=http://localhost:8000/api/userinfo
spring.security.oauth2.client.provider.casdoor.jwk-set-uri=http://localhost:8000/.well-known/jwks
spring.security.oauth2.client.provider.casdoor.user-name-attribute=name